### ISSUE TITLE
Emoji

### ISSUE THREAD

**Issue by eartharoid** [Left4Craft/left4bot#3]
Replace Unicode emoji characters in messages with the emoji name (like `:thumbsup:`) before sending, or maybe something like `:)` instead of `:smile:` etc for faces.

**Comment by CaptnSisko** [comment]
This is doable, but it would require manually writing a map of discord emojis to in-game chat emojis. There are also some emojis like "poglin" which have no clear in-game representation

**Comment by eartharoid** [comment]
We should be able to use the emoji name for custom emoji like "poglin" as well.

**Comment by BTELNYY** [comment]
I am taking this on

**Comment by BTELNYY** [comment]
Question, which part of the code handles this?
@CaptnSisko

**Comment by eartharoid** [comment]
> Question, which part of the code handles this?
> @CaptnSisko 

https://www.github.com/Left4Craft/Left4Bot/tree/master/index.js starting from line 254

**Comment by BTELNYY** [comment]
> 
> 
> > Question, which part of the code handles this?
> > @CaptnSisko
> 
> https://www.github.com/Left4Craft/Left4Bot/tree/master/index.js starting from line 254

ok thx
